[project]
name = "inventory"
version = "0.1.0"
requires-python = ">=3.13"

[dependency-groups]
dev = ["fastapi[standard]>=0.115.11"]

[tool.ruff]
line-length = 100
lint.select = ["ALL"]
lint.ignore = ["D"]

[tool.pyright]
typeCheckingMode = "strict"
