[project]
name = "inventory"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.11",
    "pydantic-settings>=2.8.1",
 "sqlmodel>=0.0.24",
]

[tool.ruff]
line-length = 100
lint.select = ["ALL"]
lint.ignore = ["D"]

[tool.pyright]
typeCheckingMode = "strict"
